# Generated by Django 4.0.3 on 2022-03-22 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitnessclub', '0002_moreimages'),
    ]

    operations = [
        migrations.AddField(
            model_name='moreimages',
            name='title',
            field=models.CharField(default=1, max_length=126),
            preserve_default=False,
        ),
    ]
